controller_list:
  - name: fake_whole_group_controller
    joints:
      - x_axis_joint
      - y_axis_joint
      - rotate_axis_joint
      - rodclimbing_joint1
      - rodclimbing_joint2
      - shoulder_joint
      - upperArm_joint
      - foreArm_joint
      - wrist1_joint
      - wrist2_joint
      - wrist3_joint
  - name: fake_endeffector_group_controller
    joints:
      []
  - name: fake_base_group_controller
    joints:
      - x_axis_joint
      - y_axis_joint
      - rotate_axis_joint
  - name: fake_rod_climbing_group_controller
    joints:
      - rodclimbing_joint1
      - rodclimbing_joint2
  - name: fake_arm_group_controller
    joints:
      - shoulder_joint
      - upperArm_joint
      - foreArm_joint
      - wrist1_joint
      - wrist2_joint
      - wrist3_joint
  - name: fake_whole_group2_controller
    joints:
      - x_axis_joint
      - y_axis_joint
      - rotate_axis_joint
      - rodclimbing_joint1
      - rodclimbing_joint2
      - shoulder_joint
      - upperArm_joint
      - foreArm_joint
      - wrist1_joint
      - wrist2_joint
      - wrist3_joint