controller_list:
  - name: fake_rot_controller
    joints:
      - upper_joint
      - rotator_joint
  - name: fake_ur_controller
    joints:
      - joint_ur1
      - joint_ur2
      - joint_ur3
      - joint_ur4
      - joint_ur5
      - joint_ur6
  - name: fake_move_controller
    joints:
      - x_joint
      - y_joint
      - r_joint