# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: rot
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - x_joint
    - y_joint
    - r_joint
    - upper_joint
    - rotator_joint
    - joint_ur1
    - joint_ur2
    - joint_ur3
    - joint_ur4
    - joint_ur5
    - joint_ur6
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []