xianquzhe1:
  arm_joint_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint_ur1
      - joint_ur2
      - joint_ur3
      - joint_ur4
      - joint_ur5
      - joint_ur6

    gains:
      joint_ur1:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint_ur2:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint_ur3:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint_ur4:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint_ur5:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint_ur6:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}

  up_joint_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - Upper_joint

    gains:
      Upper_joint:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}

